#  Topic Modeling and Trend Detection in Large Text Corpora

Topic modeling is a technique in natural language processing (NLP) and machine learning that aims to uncover latent thematic structures within a collection of texts. Topic modelling is a system learning technique that robotically discovers the principle themes or "topics" representing a huge document collection. The intention of topic modelling is to discover the hidden semantic systems within textual content facts, permitting customers to arrange, apprehend, and summarize the data in a manner that is each green and insightful.

## Arxiv Dataset
For this project we will use the Arxiv dataset which is a mirror of the original ArXiv data. For nearly 30 years, ArXiv has served the public and research communities by providing open access to scholarly articles, from the vast branches of physics to the many subdisciplines of computer science to everything in between, including math, statistics, electrical engineering, quantitative biology, and economics. This rich corpus of information offers significant, but sometimes overwhelming depth. Since the full arXiv dataset is quite large (approximately 1.1 TB and continuously growing), for the purposes of this project I will be using only the first 40,000 rows to reduce resource usage and ensure faster processing during development and experimentation.

### Install Bertopic

In [ ]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.3-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.0.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.55.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.34.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.14.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.1.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Collecting nvidia-nccl-cu12==2.21.5 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.8.3)
Downloading bertopic-0.17.3-py3-none-any.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.0/153.0 kB 12.1 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 87.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 63.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 48.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 97.4 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bertopic
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.23.4
    Uninstalling nvidia-nccl-cu12-2.23.4:
      Successfully uninstalled nvidia-nccl-cu12-2.23.4
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bertopic-0.17.3 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Import the necessary libraries

In [ ]:
from umap import UMAP
import pandas as pd
from hdbscan import HDBSCAN
from sklearn.cluster import KMeans
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
from bertopic import BERTopic
from sklearn.preprocessing import OneHotEncoder
from bertopic.representation import KeyBERTInspired,MaximalMarginalRelevance
from bertopic.dimensionality import BaseDimensionalityReduction
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.metrics import silhouette_score,calinski_harabasz_score,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

### Fetch dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/arxiv-40k.csv')

In [ ]:
dataset

,update_date,title,journal-ref,submitter,authors,doi,comments,categories,abstract,id,license,report-no,versions,authors_parsed
0,2008-11-26,Calculation of prompt diphoton production cros...,"Phys.Rev.D76:013009,2007",Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",10.1103/PhysRevD.76.013009,"37 pages, 15 figures; published version",hep-ph,A fully differential calculation in perturba...,704.0001,NaN,ANL-HEP-PR-07-12,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...","[['Balázs', 'C.', ''], ['Berger', 'E. L.', '']..."
1,2008-12-13,Sparsity-certifying Graph Decompositions,NaN,Louis Theran,Ileana Streinu and Louis Theran,NaN,To appear in Graphs and Combinatorics,math.CO cs.CG,"We describe a new algorithm, the $(k,\ell)$-...",704.0002,http://arxiv.org/licenses/nonexclusive-distrib...,NaN,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...","[['Streinu', 'Ileana', ''], ['Theran', 'Louis'..."
2,2008-01-13,The evolution of the Earth-Moon system based o...,NaN,Hongjun Pan,Hongjun Pan,NaN,"23 pages, 3 figures",physics.gen-ph,The evolution of Earth-Moon system is descri...,704.0003,NaN,NaN,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...","[['Pan', 'Hongjun', '']]"
3,2007-05-23,A determinant of Stirling cycle numbers counts...,NaN,David Callan,David Callan,NaN,11 pages,math.CO,We show that a determinant of Stirling cycle...,704.0004,NaN,NaN,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...","[['Callan', 'David', '']]"
4,2013-10-15,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,"Illinois J. Math. 52 (2008) no.2, 681-689",Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,NaN,NaN,math.CA math.FA,In this paper we show how to compute the $\L...,704.0005,NaN,NaN,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...","[['Abu-Shammala', 'Wael', ''], ['Torchinsky', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2008-11-26,Flavorful Supersymmetry,"Phys.Rev.D77:075006,2008",Yasunori Nomura,"Yasunori Nomura, Michele Papucci, Daniel Stola...",10.1103/PhysRevD.77.075006,"20 pages; typos corrected, comments added, to ...",hep-ph,Weak scale supersymmetry provides elegant so...,712.2074,NaN,UCB-PTH-07/25,"[{'version': 'v1', 'created': 'Thu, 13 Dec 200...","[['Nomura', 'Yasunori', ''], ['Papucci', 'Mich..."
39996,2011-07-20,"($\ell,0)$-Carter partitions, a generating fun...","Electronic Journal of Combinatorics, Volume 15...",Chris Berg,"Chris Berg, Monica Vazirani",NaN,NaN,math.CO math.RT,In this paper we give an alternate combinato...,712.2075,http://arxiv.org/licenses/nonexclusive-distrib...,NaN,"[{'version': 'v1', 'created': 'Thu, 13 Dec 200...","[['Berg', 'Chris', ''], ['Vazirani', 'Monica',..."
39997,2007-12-20,On the irreducible representations of a finite...,NaN,Benjamin Steinberg,"Olexandr Ganyushkin, Volodymyr Mazorchuk and B...",NaN,NaN,math.RT math.GR,"Work of Clifford, Munn and Ponizovski{\u\i} ...",712.2076,NaN,NaN,"[{'version': 'v1', 'created': 'Thu, 13 Dec 200...","[['Ganyushkin', 'Olexandr', ''], ['Mazorchuk',..."
39998,2009-11-13,The Formation of Constellation III in the Larg...,NaN,Jason Harris,Jason Harris and Dennis Zaritsky,10.1071/AS07037,Accepted for publication in the Publications o...,astro-ph,We present a detailed reconstruction of the ...,712.2077,NaN,NaN,"[{'version': 'v1', 'created': 'Thu, 13 Dec 200...","[['Harris', 'Jason', ''], ['Zaritsky', 'Dennis..."
39999,2007-12-14,Algebraic Solution of the Harmonic Oscillator ...,NaN,Zvonimir Hlousek,"K. Gemba, Z. T. Hlousek and Z. Papp",NaN,NaN,quant-ph,In quantum mechanics with minimal length unc...,712.2078,NaN,NaN,"[{'version': 'v1', 'created': 'Thu, 13 Dec 200...","[['Gemba', 'K.', ''], ['Hlousek', 'Z. T.', '']..."

### Data Preprocessing

In [ ]:
dataset.isnull().sum()

update_date           0
title                 0
journal-ref       19270
submitter             0
authors               0
doi               15629
comments           4709
categories            0
abstract              0
id                    0
license           36261
report-no         36055
versions              0
authors_parsed        0
dtype: int64

In [ ]:
dataset = dataset.drop(columns=['update_date','title','journal-ref','submitter','authors','doi','comments','id','license','report-no','versions','authors_parsed'],axis=1)
dataset

            categories                                           abstract
0               hep-ph    A fully differential calculation in perturba...
1        math.CO cs.CG    We describe a new algorithm, the $(k,\ell)$-...
2       physics.gen-ph    The evolution of Earth-Moon system is descri...
3              math.CO    We show that a determinant of Stirling cycle...
4      math.CA math.FA    In this paper we show how to compute the $\L...
...                ...                                                ...
39995           hep-ph    Weak scale supersymmetry provides elegant so...
39996  math.CO math.RT    In this paper we give an alternate combinato...
39997  math.RT math.GR    Work of Clifford, Munn and Ponizovski{\u\i} ...
39998         astro-ph    We present a detailed reconstruction of the ...
39999         quant-ph    In quantum mechanics with minimal length unc...

[40000 rows x 2 columns]

In [ ]:
threshold = 334
val_counts = dataset['categories'].value_counts()
rare_categories = val_counts[val_counts < threshold].index
dataset['categories'] = dataset['categories'].apply(
    lambda x: 'other' if x in rare_categories else x
)

In [ ]:
dataset['categories'].value_counts()

categories
other                 20024
astro-ph               6720
hep-ph                 2222
quant-ph               1723
hep-th                 1525
cond-mat.mtrl-sci       843
gr-qc                   804
cond-mat.mes-hall       697
hep-ex                  632
nucl-th                 586
cond-mat.str-el         575
cond-mat.stat-mech      530
math-ph math.MP         466
cond-mat.other          447
math.PR                 433
math.AG                 397
math.CO                 353
hep-lat                 352
cs.IT math.IT           337
math.DG                 334
Name: count, dtype: int64

In [ ]:
len(dataset['categories'].value_counts())

20

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    dataset['abstract'], dataset['categories'], test_size=0.2,
    stratify=dataset['categories'], random_state=42
)

## Create the BertTopic unsupervised Model 1

In [ ]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Step 3 - Cluster reduced embeddings
hdbscan_model = HDBSCAN(min_cluster_size=15,metric='euclidean', cluster_selection_method='eom', prediction_data=True)

# Step 4 - Tokenize topics
vectorizer_model = CountVectorizer(stop_words="english")

# Step 5 - Create topic representation
ctfidf_model = ClassTfidfTransformer()

# Step 6 - (Optional) Fine-tune topic representations with
# a `bertopic.representation` model
representation_model = KeyBERTInspired()

# All steps together
topic_model = BERTopic(
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic representations
)

In [ ]:
topics,probs = topic_model.fit_transform(X_train.tolist())

### Evaluation on the BertTopic model

In [ ]:
embeddings = topic_model.umap_model.embedding_
mask = np.array(topics) != -1
filtered_topics = np.array(topics)[mask]

print(f"Silhouette: {silhouette_score(embeddings[mask], filtered_topics):.3f}")
print(f"CH Index: {calinski_harabasz_score(embeddings[mask], filtered_topics):.0f}")

Silhouette: 0.536
CH Index: 22889

### The most frequent topics

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,14677,-1_gamma_transition_evolution_dynamics,"[gamma, transition, evolution, dynamics, densi...",[ Motivated by the possibility of creating no...
1,0,1257,0_quantum_bosons_entanglement_scattering,"[quantum, bosons, entanglement, scattering, ha...",[ The physics of quantum degenerate Fermi gas...
2,1,413,1_minimax_asymptotic_models_likelihood,"[minimax, asymptotic, models, likelihood, risk...",[ We consider the problem of estimating the u...
3,2,353,2_scattering_microscopic_particle_coulomb,"[scattering, microscopic, particle, coulomb, d...",[ Properties of effective interactions in neu...
4,3,315,3_galactic_spectral_spectra_flux,"[galactic, spectral, spectra, flux, luminosity...",[ We report on two Chandra observations of th...
...,...,...,...,...,...
228,227,15,227_dynamical_bound_models_gravitationally,"[dynamical, bound, models, gravitationally, co...","[ In young star clusters, the density can be ..."
229,228,15,228_boron_flux_superconductivity_reactive,"[boron, flux, superconductivity, reactive, tc,...",[ The effect of the quality of starting powde...
230,229,15,229_worlds_renormalizable_evolutions_doublets,"[worlds, renormalizable, evolutions, doublets,...",[ We present a simple and realistic model of ...
231,230,15,230_cosmological_cosmic_stars_intergalactic,"[cosmological, cosmic, stars, intergalactic, s...",[ We present numerical simulations of how a 1...
232,231,15,231_anisotropies_sparse_bursts_astrophysical,"[anisotropies, sparse, bursts, astrophysical, ...",[ The arrival directions of ultrahigh energy ...

### Frequent words from the second most frequent topic

In [ ]:
topic_model.get_topic(0)

[('quantum', np.float32(0.24134642)),
 ('bosons', np.float32(0.2407646)),
 ('entanglement', np.float32(0.2400794)),
 ('scattering', np.float32(0.21828768)),
 ('harmonic', np.float32(0.19498764)),
 ('potential', np.float32(0.19493227)),
 ('trapping', np.float32(0.18285118)),
 ('fermions', np.float32(0.18015389)),
 ('lattices', np.float32(0.16824923)),
 ('excitation', np.float32(0.16710997))]

### Info about the documents clustered in these topics

In [ ]:
topic_model.get_document_info(X_train)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,A detailed comparison of the expressions for...,2,2_scattering_microscopic_particle_coulomb,"[scattering, microscopic, particle, coulomb, d...",[ Properties of effective interactions in neu...,scattering - microscopic - particle - coulomb ...,1.000000,False
1,This is an expanded version of our earlier p...,58,58_conjectures_asymptotic_conjecture_infinitely,"[conjectures, asymptotic, conjecture, infinite...",[ A classical problem in analytic number theo...,conjectures - asymptotic - conjecture - infini...,0.234291,False
2,Solutions to conservation laws satisfy the m...,-1,-1_gamma_transition_evolution_dynamics,"[gamma, transition, evolution, dynamics, densi...",[ Motivated by the possibility of creating no...,gamma - transition - evolution - dynamics - de...,0.000000,False
3,By means of the 10-resonance unitary and ana...,127,127_renormalization_quark_nucleon_chiral,"[renormalization, quark, nucleon, chiral, hype...",[ We study a new nucleon resonance from eta p...,renormalization - quark - nucleon - chiral - h...,1.000000,False
4,A pedigree is a directed graph that describe...,-1,-1_gamma_transition_evolution_dynamics,"[gamma, transition, evolution, dynamics, densi...",[ Motivated by the possibility of creating no...,gamma - transition - evolution - dynamics - de...,0.000000,False
...,...,...,...,...,...,...,...,...
31995,The high pressure phase diagram of CsC8 grap...,5,5_symmetry_scattering_nanoribbon_fermions,"[symmetry, scattering, nanoribbon, fermions, n...",[ We report the existence of zero energy surf...,symmetry - scattering - nanoribbon - fermions ...,0.338843,False
31996,We present a preliminary set of updated NLO ...,106,106_qcd_photons_hadron_photon,"[qcd, photons, hadron, photon, data, lhc, tran...",[ With the knowledge of diffractive parton de...,qcd - photons - hadron - photon - data - lhc -...,0.634735,False
31997,We have investigated the doping dependence o...,19,19_isotope_spectroscopy_scattering_observed,"[isotope, spectroscopy, scattering, observed, ...",[ Pairing of electrons in conventional superc...,isotope - spectroscopy - scattering - observed...,0.667108,False
31998,We calculate the O($\eps$)--term of the two-...,110,110_feynman_quark_qcd_renormalization,"[feynman, quark, qcd, renormalization, propaga...",[ The dynamically generated effective gluon m...,feynman - quark - qcd - renormalization - prop...,0.530741,False
31999,Perturbations in the ionization fraction aft...,-1,-1_gamma_transition_evolution_dynamics,"[gamma, transition, evolution, dynamics, densi...",[ Motivated by the possibility of creating no...,gamma - transition - evolution - dynamics - de...,0.000000,False

## Data Visualization of the topics

In [ ]:
topic_model.visualize_barchart(top_n_topics=20,n_words=10)

In [ ]:
topic_model.visualize_heatmap()

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_hierarchy()

In [ ]:
topics_per_class = topic_model.topics_per_class(X_train, classes=y_train)
topic_model.visualize_topics_per_class(topics_per_class)

In [ ]:
from collections import Counter
import numpy as np


# 2️⃣ Map each topic to the most frequent class in that topic
topic_to_class = {}
for topic_id in set(topics):
    if topic_id == -1:  # -1 is usually "outlier topic" in BERTopic
        continue
    # Get indices of documents in this topic
    idxs = [i for i, t in enumerate(topics) if t == topic_id]
    # Get their classes
    classes_in_topic = [y_train.iloc[i] for i in idxs]
    # Find the most common class
    most_common_class = Counter(classes_in_topic).most_common(1)[0][0]
    topic_to_class[topic_id] = most_common_class

# 3️⃣ Show mapping
for t, c in topic_to_class.items():
    print(f"Topic {t} → Class '{c}'")

Topic 0 → Class 'other'
Topic 1 → Class 'other'
Topic 2 → Class 'nucl-th'
Topic 3 → Class 'astro-ph'
Topic 4 → Class 'hep-ph'
Topic 5 → Class 'other'
Topic 6 → Class 'math.AG'
Topic 7 → Class 'other'
Topic 8 → Class 'cs.IT math.IT'
Topic 9 → Class 'other'
Topic 10 → Class 'other'
Topic 11 → Class 'other'
Topic 12 → Class 'hep-th'
Topic 13 → Class 'other'
Topic 14 → Class 'cond-mat.mes-hall'
Topic 15 → Class 'astro-ph'
Topic 16 → Class 'cond-mat.mes-hall'
Topic 17 → Class 'other'
Topic 18 → Class 'cond-mat.stat-mech'
Topic 19 → Class 'other'
Topic 20 → Class 'astro-ph'
Topic 21 → Class 'other'
Topic 22 → Class 'astro-ph'
Topic 23 → Class 'other'
Topic 24 → Class 'other'
Topic 25 → Class 'other'
Topic 26 → Class 'other'
Topic 27 → Class 'astro-ph'
Topic 28 → Class 'quant-ph'
Topic 29 → Class 'astro-ph'
Topic 30 → Class 'astro-ph'
Topic 31 → Class 'quant-ph'
Topic 32 → Class 'other'
Topic 33 → Class 'astro-ph'
Topic 34 → Class 'hep-ex'
Topic 35 → Class 'other'
Topic 36 → Class 'other'
Topic 37 → Class 'other'
Topic 38 → Class 'other'
Topic 39 → Class 'math.PR'
Topic 40 → Class 'cond-mat.mtrl-sci'
Topic 41 → Class 'other'
Topic 42 → Class 'other'
Topic 43 → Class 'astro-ph'
Topic 44 → Class 'other'
Topic 45 → Class 'other'
Topic 46 → Class 'other'
Topic 47 → Class 'hep-ex'
Topic 48 → Class 'other'
Topic 49 → Class 'hep-lat'
Topic 50 → Class 'hep-ph'
Topic 51 → Class 'hep-ph'
Topic 52 → Class 'astro-ph'
Topic 53 → Class 'other'
Topic 54 → Class 'quant-ph'
Topic 55 → Class 'astro-ph'
Topic 56 → Class 'other'
Topic 57 → Class 'other'
Topic 58 → Class 'other'
Topic 59 → Class 'astro-ph'
Topic 60 → Class 'astro-ph'
Topic 61 → Class 'other'
Topic 62 → Class 'other'
Topic 63 → Class 'gr-qc'
Topic 64 → Class 'other'
Topic 65 → Class 'other'
Topic 66 → Class 'astro-ph'
Topic 67 → Class 'other'
Topic 68 → Class 'other'
Topic 69 → Class 'other'
Topic 70 → Class 'astro-ph'
Topic 71 → Class 'other'
Topic 72 → Class 'other'
Topic 73 → Class 'other'
Topic 74 → Class 'other'
Topic 75 → Class 'other'
Topic 76 → Class 'other'
Topic 77 → Class 'other'
Topic 78 → Class 'other'
Topic 79 → Class 'cond-mat.str-el'
Topic 80 → Class 'astro-ph'
Topic 81 → Class 'astro-ph'
Topic 82 → Class 'other'
Topic 83 → Class 'other'
Topic 84 → Class 'other'
Topic 85 → Class 'math.CO'
Topic 86 → Class 'other'
Topic 87 → Class 'math.DG'
Topic 88 → Class 'gr-qc'
Topic 89 → Class 'cond-mat.str-el'
Topic 90 → Class 'other'
Topic 91 → Class 'other'
Topic 92 → Class 'astro-ph'
Topic 93 → Class 'gr-qc'
Topic 94 → Class 'other'
Topic 95 → Class 'astro-ph'
Topic 96 → Class 'other'
Topic 97 → Class 'other'
Topic 98 → Class 'other'
Topic 99 → Class 'other'
Topic 100 → Class 'other'
Topic 101 → Class 'astro-ph'
Topic 102 → Class 'other'
Topic 103 → Class 'astro-ph'
Topic 104 → Class 'other'
Topic 105 → Class 'other'
Topic 106 → Class 'hep-ph'
Topic 107 → Class 'other'
Topic 108 → Class 'other'
Topic 109 → Class 'hep-th'
Topic 110 → Class 'hep-ph'
Topic 111 → Class 'cs.IT math.IT'
Topic 112 → Class 'other'
Topic 113 → Class 'other'
Topic 114 → Class 'other'
Topic 115 → Class 'other'
Topic 116 → Class 'hep-th'
Topic 117 → Class 'quant-ph'
Topic 118 → Class 'other'
Topic 119 → Class 'other'
Topic 120 → Class 'other'
Topic 121 → Class 'hep-th'
Topic 122 → Class 'other'
Topic 123 → Class 'hep-th'
Topic 124 → Class 'other'
Topic 125 → Class 'other'
Topic 126 → Class 'hep-ph'
Topic 127 → Class 'nucl-th'
Topic 128 → Class 'cond-mat.str-el'
Topic 129 → Class 'other'
Topic 130 → Class 'other'
Topic 131 → Class 'other'
Topic 132 → Class 'other'
Topic 133 → Class 'other'
Topic 134 → Class 'other'
Topic 135 → Class 'other'
Topic 136 → Class 'other'
Topic 137 → Class 'astro-ph'
Topic 138 → Class 'other'
Topic 139 → Class 'other'
Topic 140 → Class 'other'
Topic 141 → Class 'hep-th'
Topic 142 → Class 'astro-ph'
Topic 143 → Class 'other'
Topic 144 → Class 'astro-ph'
Topic 145 → Class 'other'
Topic 146 → Class 'astro-ph'
Topic 147 → Class 'other'
Topic 148 → Class 'other'
Topic 149 → Class 'other'
Topic 150 → Class 'astro-ph'
Topic 151 → Class 'other'
Topic 152 → Class 'hep-th'
Topic 153 → Class 'cond-mat.str-el'
Topic 154 → Class 'astro-ph'
Topic 155 → Class 'hep-lat'
Topic 156 → Class 'other'
Topic 157 → Class 'other'
Topic 158 → Class 'other'
Topic 159 → Class 'hep-ph'
Topic 160 → Class 'other'
Topic 161 → Class 'astro-ph'
Topic 162 → Class 'other'
Topic 163 → Class 'other'
Topic 164 → Class 'math.PR'
Topic 165 → Class 'nucl-th'
Topic 166 → Class 'other'
Topic 167 → Class 'other'
Topic 168 → Class 'hep-ph'
Topic 169 → Class 'quant-ph'
Topic 170 → Class 'astro-ph'
Topic 171 → Class 'other'
Topic 172 → Class 'other'
Topic 173 → Class 'hep-ph'
Topic 174 → Class 'other'
Topic 175 → Class 'other'
Topic 176 → Class 'other'
Topic 177 → Class 'other'
Topic 178 → Class 'gr-qc'
Topic 179 → Class 'astro-ph'
Topic 180 → Class 'other'
Topic 181 → Class 'nucl-th'
Topic 182 → Class 'math.PR'
Topic 183 → Class 'other'
Topic 184 → Class 'other'
Topic 185 → Class 'other'
Topic 186 → Class 'other'
Topic 187 → Class 'other'
Topic 188 → Class 'astro-ph'
Topic 189 → Class 'other'
Topic 190 → Class 'other'
Topic 191 → Class 'hep-ph'
Topic 192 → Class 'other'
Topic 193 → Class 'other'
Topic 194 → Class 'other'
Topic 195 → Class 'other'
Topic 196 → Class 'astro-ph'
Topic 197 → Class 'other'
Topic 198 → Class 'hep-th'
Topic 199 → Class 'hep-th'
Topic 200 → Class 'gr-qc'
Topic 201 → Class 'astro-ph'
Topic 202 → Class 'other'
Topic 203 → Class 'other'
Topic 204 → Class 'hep-th'
Topic 205 → Class 'other'
Topic 206 → Class 'other'
Topic 207 → Class 'other'
Topic 208 → Class 'quant-ph'
Topic 209 → Class 'other'
Topic 210 → Class 'other'
Topic 211 → Class 'other'
Topic 212 → Class 'other'
Topic 213 → Class 'other'
Topic 214 → Class 'other'
Topic 215 → Class 'other'
Topic 216 → Class 'astro-ph'
Topic 217 → Class 'hep-th'
Topic 218 → Class 'astro-ph'
Topic 219 → Class 'other'
Topic 220 → Class 'other'
Topic 221 → Class 'astro-ph'
Topic 222 → Class 'other'
Topic 223 → Class 'other'
Topic 224 → Class 'other'
Topic 225 → Class 'quant-ph'
Topic 226 → Class 'astro-ph'
Topic 227 → Class 'astro-ph'
Topic 228 → Class 'other'
Topic 229 → Class 'other'
Topic 230 → Class 'astro-ph'
Topic 231 → Class 'astro-ph'

In [ ]:
mapped_train_labels = [topic_to_class.get(t, "Unknown") for t in topics]

# Prepare topic IDs as feature for classifier
X_topics_train = pd.DataFrame(topics, columns=["topic"])
encoder = OneHotEncoder(handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_topics_train)

In [ ]:
X_topics_train

       topic
0          2
1         58
2         -1
3        127
4         -1
...      ...
31995      5
31996    106
31997     19
31998    110
31999     -1

[32000 rows x 1 columns]

In [ ]:
clf = RandomForestClassifier(n_estimators=200,criterion='entropy', random_state=42)
clf.fit(X_train_encoded, mapped_train_labels)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=42)

In [ ]:
topics_test, _ = topic_model.transform(X_test.tolist())
X_test_topics = pd.DataFrame(topics_test, columns=["topic"])
X_test_encoded = encoder.transform(X_test_topics)

# Predict classes on test set
y_pred = clf.predict(X_test_encoded)

# Evaluate
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

           Unknown       0.00      0.00      0.00         0
          astro-ph       0.92      0.44      0.59      1344
 cond-mat.mes-hall       0.49      0.26      0.34       139
 cond-mat.mtrl-sci       0.45      0.05      0.10       169
    cond-mat.other       0.00      0.00      0.00        90
cond-mat.stat-mech       0.57      0.24      0.33       106
   cond-mat.str-el       0.65      0.30      0.41       115
     cs.IT math.IT       0.70      0.76      0.73        67
             gr-qc       0.43      0.19      0.26       161
            hep-ex       0.80      0.37      0.51       126
           hep-lat       0.60      0.21      0.32        70
            hep-ph       0.78      0.23      0.35       444
            hep-th       0.67      0.23      0.35       305
   math-ph math.MP       0.00      0.00      0.00        93
           math.AG       0.67      0.38      0.48        79
           math.CO       0.42      0.07      0.12        71
           math.DG       0.55      0.09      0.15        67
           math.PR       0.70      0.30      0.42        87
           nucl-th       0.52      0.39      0.45       117
             other       0.73      0.40      0.52      4005
          quant-ph       0.78      0.23      0.36       345

          accuracy                           0.35      8000
         macro avg       0.54      0.25      0.32      8000
      weighted avg       0.72      0.35      0.47      8000

In [ ]:
clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf.fit(X_train_encoded, mapped_train_labels)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
topics_test, _ = topic_model.transform(X_test.tolist())
X_test_topics = pd.DataFrame(topics_test, columns=["topic"])
X_test_encoded = encoder.transform(X_test_topics)

# Predict classes on test set
y_pred = clf.predict(X_test_encoded)

# Evaluate
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

           Unknown       0.00      0.00      0.00         0
          astro-ph       0.92      0.44      0.59      1344
 cond-mat.mes-hall       0.49      0.26      0.34       139
 cond-mat.mtrl-sci       0.45      0.05      0.10       169
    cond-mat.other       0.00      0.00      0.00        90
cond-mat.stat-mech       0.57      0.24      0.33       106
   cond-mat.str-el       0.65      0.30      0.41       115
     cs.IT math.IT       0.70      0.76      0.73        67
             gr-qc       0.43      0.19      0.26       161
            hep-ex       0.80      0.37      0.51       126
           hep-lat       0.60      0.21      0.32        70
            hep-ph       0.78      0.23      0.35       444
            hep-th       0.67      0.23      0.35       305
   math-ph math.MP       0.00      0.00      0.00        93
           math.AG       0.67      0.38      0.48        79
           math.CO       0.42      0.07      0.12        71
           math.DG       0.55      0.09      0.15        67
           math.PR       0.70      0.30      0.42        87
           nucl-th       0.52      0.39      0.45       117
             other       0.73      0.40      0.52      4005
          quant-ph       0.78      0.23      0.36       345

          accuracy                           0.35      8000
         macro avg       0.54      0.25      0.32      8000
      weighted avg       0.72      0.35      0.47      8000

## Create BertTopic Model unsupervised 2

In [ ]:
embedding_model = SentenceTransformer("all-mpnet-base-v2")


# Step 3 - Cluster reduced embeddings
hdbscan_model = HDBSCAN(min_cluster_size=15,allow_single_cluster=True,metric='euclidean', algorithm='best', cluster_selection_method='eom', prediction_data=True)

# Step 4 - Tokenize topics
vectorizer_model = TfidfVectorizer(stop_words="english")

# Step 5 - Create topic representation
ctfidf_model = ClassTfidfTransformer()
# Step 6 - (Optional) Fine-tune topic representations with
# a `bertopic.representation` model
representation_model = KeyBERTInspired()

# All steps together
topic_model_2 = BERTopic(
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model = ctfidf_model,
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic representations
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
topics, _ = topic_model_2.fit_transform(X_train.tolist())

### Evaluation

In [ ]:
embeddings = topic_model_2.umap_model.embedding_
mask = np.array(topics) != -1
filtered_topics = np.array(topics)[mask]

print(f"Silhouette: {silhouette_score(embeddings[mask], filtered_topics):.3f}")
print(f"CH Index: {calinski_harabasz_score(embeddings[mask], filtered_topics):.0f}")

Silhouette: 0.578
CH Index: 6958

### The most frequent topics

In [ ]:
topic_model_2.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,11184,-1_nucleon_proton_quark_finite,"[nucleon, proton, quark, finite, qcd, lhc, dec...",[ We investigate whether a mass scale for ele...
1,0,5200,0_abundances_observations_redshifts_observed,"[abundances, observations, redshifts, observed...",[ Elliptical galaxies probably host the most ...
2,1,925,1_conformational_conformation_particles_disloc...,"[conformational, conformation, particles, disl...","[ Soft materials, such as colloidal suspensio..."
3,2,724,2_fermions_fermionic_solitons_quantum,"[fermions, fermionic, solitons, quantum, super...",[ We study the effect of a one dimensional op...
4,3,556,3_superconductivity_superconductors_supercondu...,"[superconductivity, superconductors, supercond...",[ We analyze the ground state properties of a...
...,...,...,...,...,...
206,205,16,205_fermions_spinons_quantization_fermionic,"[fermions, spinons, quantization, fermionic, f...",[ The (discrete) Gross-Neveu model is studied...
207,206,16,206_pulsars_hadronic_gravitational_ellipticity,"[pulsars, hadronic, gravitational, ellipticity...","[ Recently, observations of compact stars hav..."
208,207,15,207_quantum_flaws_qubits_3db,"[quantum, flaws, qubits, 3db, entanglement, qc...",[ We analyze a possibility of using the two q...
209,208,15,208_atoms_isomers_pseudopotential_orbitals,"[atoms, isomers, pseudopotential, orbitals, an...","[ Theoretical studies on the geometry, electr..."
210,209,15,209_hypersurfaces_picard_orbit_projective,"[hypersurfaces, picard, orbit, projective, ell...",[ We produce a new family of polynomials f(x)...

### Frequent words from the second most frequent topic

In [ ]:
topic_model_2.get_topic(0)

[('abundances', np.float32(0.21294507)),
 ('observations', np.float32(0.1940336)),
 ('redshifts', np.float32(0.18382359)),
 ('observed', np.float32(0.17563762)),
 ('abundance', np.float32(0.16644563)),
 ('quasars', np.float32(0.16623583)),
 ('variability', np.float32(0.16139035)),
 ('massive', np.float32(0.15517385)),
 ('kpc', np.float32(0.13751893)),
 ('stars', np.float32(0.13693151))]

### Info about the documents clustered in these topics

In [ ]:
topic_model_2.get_document_info(X_train)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,A detailed comparison of the expressions for...,-1,-1_nucleon_proton_quark_finite,"[nucleon, proton, quark, finite, qcd, lhc, dec...",[ We investigate whether a mass scale for ele...,nucleon - proton - quark - finite - qcd - lhc ...,0.000000,False
1,This is an expanded version of our earlier p...,41,41_pseudosquares_q_k_sums_psi_n,"[pseudosquares, q_k, sums, psi_n, sumset, p_2,...",[ We prove that there are infinitely often pa...,pseudosquares - q_k - sums - psi_n - sumset - ...,0.448170,False
2,Solutions to conservation laws satisfy the m...,-1,-1_nucleon_proton_quark_finite,"[nucleon, proton, quark, finite, qcd, lhc, dec...",[ We investigate whether a mass scale for ele...,nucleon - proton - quark - finite - qcd - lhc ...,0.000000,False
3,By means of the 10-resonance unitary and ana...,30,30_parameterizations_polarizabilities_relativi...,"[parameterizations, polarizabilities, relativi...",[ The meson-cloud model of the nucleon consis...,parameterizations - polarizabilities - relativ...,1.000000,False
4,A pedigree is a directed graph that describe...,149,149_recombination_data_reconstructed_vectors,"[recombination, data, reconstructed, vectors, ...",[ Phylogenetic networks are a generalization ...,recombination - data - reconstructed - vectors...,0.378266,False
...,...,...,...,...,...,...,...,...
31995,The high pressure phase diagram of CsC8 grap...,7,7_magnetic_coulomb_dirac_fermi,"[magnetic, coulomb, dirac, fermi, electron, el...",[ We study the effects of metallic doping on ...,magnetic - coulomb - dirac - fermi - electron ...,0.429950,False
31996,We present a preliminary set of updated NLO ...,-1,-1_nucleon_proton_quark_finite,"[nucleon, proton, quark, finite, qcd, lhc, dec...",[ We investigate whether a mass scale for ele...,nucleon - proton - quark - finite - qcd - lhc ...,0.000000,False
31997,We have investigated the doping dependence o...,3,3_superconductivity_superconductors_supercondu...,"[superconductivity, superconductors, supercond...",[ We analyze the ground state properties of a...,superconductivity - superconductors - supercon...,1.000000,False
31998,We calculate the O($\eps$)--term of the two-...,136,136_transcendentality_unitarity_feynman_photon,"[transcendentality, unitarity, feynman, photon...",[ Feynman diagrams may be evaluated by Mellin...,transcendentality - unitarity - feynman - phot...,0.557707,False
31999,Perturbations in the ionization fraction aft...,0,0_abundances_observations_redshifts_observed,"[abundances, observations, redshifts, observed...",[ Elliptical galaxies probably host the most ...,abundances - observations - redshifts - observ...,1.000000,False

## Visualization of the topics

In [ ]:
topic_model_2.visualize_barchart(top_n_topics=20,n_words=8)

In [ ]:
topic_model_2.visualize_heatmap()

In [ ]:
topic_model_2.visualize_topics()

In [ ]:
topic_model_2.visualize_hierarchy()

In [ ]:
topics_per_class = topic_model_2.topics_per_class(X_train, classes=y_train)
topic_model_2.visualize_topics_per_class(topics_per_class)

In [ ]:
topic_to_class = {}
for topic_id in set(topics):
    if topic_id == -1:  # -1 is usually "outlier topic" in BERTopic
        continue
    # Get indices of documents in this topic
    idxs = [i for i, t in enumerate(topics) if t == topic_id]
    # Get their classes
    classes_in_topic = [y_train.iloc[i] for i in idxs]
    # Find the most common class
    most_common_class = Counter(classes_in_topic).most_common(1)[0][0]
    topic_to_class[topic_id] = most_common_class

# 3️⃣ Show mapping
for t, c in topic_to_class.items():
    print(f"Topic {t} → Class '{c}'")

Topic 0 → Class 'astro-ph'
Topic 1 → Class 'other'
Topic 2 → Class 'other'
Topic 3 → Class 'other'
Topic 4 → Class 'other'
Topic 5 → Class 'other'
Topic 6 → Class 'other'
Topic 7 → Class 'other'
Topic 8 → Class 'math.AG'
Topic 9 → Class 'other'
Topic 10 → Class 'other'
Topic 11 → Class 'other'
Topic 12 → Class 'math.PR'
Topic 13 → Class 'other'
Topic 14 → Class 'hep-th'
Topic 15 → Class 'other'
Topic 16 → Class 'quant-ph'
Topic 17 → Class 'hep-lat'
Topic 18 → Class 'other'
Topic 19 → Class 'nucl-th'
Topic 20 → Class 'hep-ph'
Topic 21 → Class 'quant-ph'
Topic 22 → Class 'cond-mat.mes-hall'
Topic 23 → Class 'cond-mat.str-el'
Topic 24 → Class 'hep-ph'
Topic 25 → Class 'other'
Topic 26 → Class 'other'
Topic 27 → Class 'hep-ex'
Topic 28 → Class 'other'
Topic 29 → Class 'other'
Topic 30 → Class 'other'
Topic 31 → Class 'other'
Topic 32 → Class 'cond-mat.stat-mech'
Topic 33 → Class 'other'
Topic 34 → Class 'other'
Topic 35 → Class 'hep-th'
Topic 36 → Class 'other'
Topic 37 → Class 'other'
Topic 38 → Class 'hep-ex'
Topic 39 → Class 'other'
Topic 40 → Class 'cs.IT math.IT'
Topic 41 → Class 'other'
Topic 42 → Class 'other'
Topic 43 → Class 'other'
Topic 44 → Class 'other'
Topic 45 → Class 'other'
Topic 46 → Class 'cond-mat.mes-hall'
Topic 47 → Class 'other'
Topic 48 → Class 'other'
Topic 49 → Class 'quant-ph'
Topic 50 → Class 'gr-qc'
Topic 51 → Class 'quant-ph'
Topic 52 → Class 'other'
Topic 53 → Class 'other'
Topic 54 → Class 'gr-qc'
Topic 55 → Class 'other'
Topic 56 → Class 'other'
Topic 57 → Class 'other'
Topic 58 → Class 'other'
Topic 59 → Class 'other'
Topic 60 → Class 'other'
Topic 61 → Class 'other'
Topic 62 → Class 'other'
Topic 63 → Class 'other'
Topic 64 → Class 'other'
Topic 65 → Class 'other'
Topic 66 → Class 'hep-th'
Topic 67 → Class 'astro-ph'
Topic 68 → Class 'other'
Topic 69 → Class 'other'
Topic 70 → Class 'other'
Topic 71 → Class 'other'
Topic 72 → Class 'other'
Topic 73 → Class 'other'
Topic 74 → Class 'other'
Topic 75 → Class 'math.CO'
Topic 76 → Class 'other'
Topic 77 → Class 'other'
Topic 78 → Class 'hep-ph'
Topic 79 → Class 'hep-ph'
Topic 80 → Class 'hep-th'
Topic 81 → Class 'other'
Topic 82 → Class 'cond-mat.str-el'
Topic 83 → Class 'gr-qc'
Topic 84 → Class 'other'
Topic 85 → Class 'quant-ph'
Topic 86 → Class 'other'
Topic 87 → Class 'other'
Topic 88 → Class 'other'
Topic 89 → Class 'other'
Topic 90 → Class 'other'
Topic 91 → Class 'other'
Topic 92 → Class 'gr-qc'
Topic 93 → Class 'other'
Topic 94 → Class 'other'
Topic 95 → Class 'other'
Topic 96 → Class 'other'
Topic 97 → Class 'hep-ph'
Topic 98 → Class 'other'
Topic 99 → Class 'quant-ph'
Topic 100 → Class 'hep-ph'
Topic 101 → Class 'hep-th'
Topic 102 → Class 'hep-ph'
Topic 103 → Class 'other'
Topic 104 → Class 'other'
Topic 105 → Class 'other'
Topic 106 → Class 'other'
Topic 107 → Class 'other'
Topic 108 → Class 'other'
Topic 109 → Class 'other'
Topic 110 → Class 'other'
Topic 111 → Class 'hep-ph'
Topic 112 → Class 'other'
Topic 113 → Class 'math.DG'
Topic 114 → Class 'hep-ph'
Topic 115 → Class 'other'
Topic 116 → Class 'other'
Topic 117 → Class 'other'
Topic 118 → Class 'other'
Topic 119 → Class 'other'
Topic 120 → Class 'cond-mat.mtrl-sci'
Topic 121 → Class 'hep-th'
Topic 122 → Class 'cs.IT math.IT'
Topic 123 → Class 'other'
Topic 124 → Class 'other'
Topic 125 → Class 'other'
Topic 126 → Class 'cs.IT math.IT'
Topic 127 → Class 'other'
Topic 128 → Class 'other'
Topic 129 → Class 'other'
Topic 130 → Class 'other'
Topic 131 → Class 'other'
Topic 132 → Class 'other'
Topic 133 → Class 'other'
Topic 134 → Class 'other'
Topic 135 → Class 'other'
Topic 136 → Class 'hep-ph'
Topic 137 → Class 'other'
Topic 138 → Class 'cond-mat.mtrl-sci'
Topic 139 → Class 'other'
Topic 140 → Class 'other'
Topic 141 → Class 'math.PR'
Topic 142 → Class 'other'
Topic 143 → Class 'other'
Topic 144 → Class 'other'
Topic 145 → Class 'other'
Topic 146 → Class 'other'
Topic 147 → Class 'hep-lat'
Topic 148 → Class 'other'
Topic 149 → Class 'other'
Topic 150 → Class 'other'
Topic 151 → Class 'other'
Topic 152 → Class 'other'
Topic 153 → Class 'math.AG'
Topic 154 → Class 'other'
Topic 155 → Class 'other'
Topic 156 → Class 'other'
Topic 157 → Class 'other'
Topic 158 → Class 'other'
Topic 159 → Class 'other'
Topic 160 → Class 'other'
Topic 161 → Class 'hep-th'
Topic 162 → Class 'other'
Topic 163 → Class 'gr-qc'
Topic 164 → Class 'hep-ph'
Topic 165 → Class 'other'
Topic 166 → Class 'other'
Topic 167 → Class 'hep-th'
Topic 168 → Class 'quant-ph'
Topic 169 → Class 'other'
Topic 170 → Class 'other'
Topic 171 → Class 'other'
Topic 172 → Class 'other'
Topic 173 → Class 'other'
Topic 174 → Class 'other'
Topic 175 → Class 'hep-ph'
Topic 176 → Class 'other'
Topic 177 → Class 'other'
Topic 178 → Class 'other'
Topic 179 → Class 'other'
Topic 180 → Class 'other'
Topic 181 → Class 'cond-mat.stat-mech'
Topic 182 → Class 'hep-lat'
Topic 183 → Class 'quant-ph'
Topic 184 → Class 'other'
Topic 185 → Class 'other'
Topic 186 → Class 'other'
Topic 187 → Class 'other'
Topic 188 → Class 'other'
Topic 189 → Class 'hep-ex'
Topic 190 → Class 'math-ph math.MP'
Topic 191 → Class 'hep-th'
Topic 192 → Class 'other'
Topic 193 → Class 'hep-lat'
Topic 194 → Class 'other'
Topic 195 → Class 'other'
Topic 196 → Class 'other'
Topic 197 → Class 'other'
Topic 198 → Class 'gr-qc'
Topic 199 → Class 'other'
Topic 200 → Class 'other'
Topic 201 → Class 'other'
Topic 202 → Class 'cs.IT math.IT'
Topic 203 → Class 'hep-ph'
Topic 204 → Class 'other'
Topic 205 → Class 'other'
Topic 206 → Class 'other'
Topic 207 → Class 'quant-ph'
Topic 208 → Class 'cond-mat.mtrl-sci'
Topic 209 → Class 'other'

In [ ]:
mapped_train_labels = [topic_to_class.get(t, "Unknown") for t in topics]

# Prepare topic IDs as feature for classifier
X_topics_train = pd.DataFrame(topics, columns=["topic"])
encoder = OneHotEncoder(handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_topics_train)

In [ ]:
clf = RandomForestClassifier(n_estimators=200,criterion='entropy', random_state=42)
clf.fit(X_train_encoded, mapped_train_labels)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=42)

In [ ]:
topics_test, _ = topic_model_2.transform(X_test.tolist())
X_test_topics = pd.DataFrame(topics_test, columns=["topic"])
X_test_encoded = encoder.transform(X_test_topics)

# Predict classes on test set
y_pred = clf.predict(X_test_encoded)

# Evaluate
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

           Unknown       0.00      0.00      0.00         0
          astro-ph       0.94      0.93      0.93      1344
 cond-mat.mes-hall       0.44      0.16      0.23       139
 cond-mat.mtrl-sci       0.67      0.04      0.07       169
    cond-mat.other       0.00      0.00      0.00        90
cond-mat.stat-mech       0.56      0.21      0.30       106
   cond-mat.str-el       0.56      0.25      0.35       115
     cs.IT math.IT       0.69      0.54      0.61        67
             gr-qc       0.57      0.25      0.35       161
            hep-ex       0.63      0.35      0.45       126
           hep-lat       0.64      0.60      0.62        70
            hep-ph       0.78      0.25      0.37       444
            hep-th       0.66      0.24      0.35       305
   math-ph math.MP       0.17      0.01      0.02        93
           math.AG       0.66      0.42      0.51        79
           math.CO       0.56      0.07      0.12        71
           math.DG       0.50      0.03      0.06        67
           math.PR       0.67      0.30      0.41        87
           nucl-th       0.63      0.16      0.26       117
             other       0.72      0.48      0.57      4005
          quant-ph       0.75      0.36      0.48       345

          accuracy                           0.47      8000
         macro avg       0.56      0.27      0.34      8000
      weighted avg       0.72      0.47      0.55      8000

In [ ]:
clf = DecisionTreeClassifier(criterion='entropy', random_state=42)
clf.fit(X_train_encoded, mapped_train_labels)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [ ]:
topics_test, _ = topic_model.transform(X_test.tolist())
X_test_topics = pd.DataFrame(topics_test, columns=["topic"])
X_test_encoded = encoder.transform(X_test_topics)

# Predict classes on test set
y_pred = clf.predict(X_test_encoded)

# Evaluate
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

           Unknown       0.00      0.00      0.00         0
          astro-ph       0.00      0.00      0.00      1344
 cond-mat.mes-hall       0.00      0.00      0.00       139
 cond-mat.mtrl-sci       0.00      0.00      0.00       169
    cond-mat.other       0.00      0.00      0.00        90
cond-mat.stat-mech       0.00      0.00      0.00       106
   cond-mat.str-el       0.00      0.00      0.00       115
     cs.IT math.IT       0.00      0.00      0.00        67
             gr-qc       0.06      0.02      0.03       161
            hep-ex       0.00      0.00      0.00       126
           hep-lat       0.00      0.00      0.00        70
            hep-ph       0.00      0.00      0.00       444
            hep-th       0.03      0.01      0.02       305
   math-ph math.MP       0.00      0.00      0.00        93
           math.AG       0.00      0.00      0.00        79
           math.CO       0.00      0.00      0.00        71
           math.DG       0.00      0.00      0.00        67
           math.PR       0.00      0.00      0.00        87
           nucl-th       0.00      0.00      0.00       117
             other       0.53      0.32      0.40      4005
          quant-ph       0.00      0.00      0.00       345

          accuracy                           0.16      8000
         macro avg       0.03      0.02      0.02      8000
      weighted avg       0.27      0.16      0.20      8000