#  Topic Modeling and Trend Detection in Large Text Corpora

Topic modeling is a technique in natural language processing (NLP) and machine learning that aims to uncover latent thematic structures within a collection of texts. Topic modelling is a system learning technique that robotically discovers the principle themes or "topics" representing a huge document collection. The intention of topic modelling is to discover the hidden semantic systems within textual content facts, permitting customers to arrange, apprehend, and summarize the data in a manner that is each green and insightful.

## Arxiv Dataset
For this project we will use the Arxiv dataset which is a mirror of the original ArXiv data. For nearly 30 years, ArXiv has served the public and research communities by providing open access to scholarly articles, from the vast branches of physics to the many subdisciplines of computer science to everything in between, including math, statistics, electrical engineering, quantitative biology, and economics. This rich corpus of information offers significant, but sometimes overwhelming depth. Since the full arXiv dataset is quite large (approximately 1.1 TB and continuously growing), for the purposes of this project I will be using only the first 40,000 rows to reduce resource usage and ensure faster processing during development and experimentation.

### Install Bertopic

In [ ]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.1.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.15.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.52.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.32.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.13.2)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.1.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.5.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.4.26)
Downloading bertopic-0.17.0-py3-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.6/150.6 kB 9.4 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 122.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 96.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 65.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.0 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 95.1 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bertopic
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bertopic-0.17.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

### Import the necessary libraries

In [ ]:
from umap import UMAP
import pandas as pd
from hdbscan import HDBSCAN
from sklearn.cluster import KMeans
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired,MaximalMarginalRelevance
from bertopic.dimensionality import BaseDimensionalityReduction
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.metrics import silhouette_score,calinski_harabasz_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

### Fetch dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/arxiv-40k.csv')

In [ ]:
dataset

      update_date  ...                                     authors_parsed
0      2008-11-26  ...  [['Balázs', 'C.', ''], ['Berger', 'E. L.', '']...
1      2008-12-13  ...  [['Streinu', 'Ileana', ''], ['Theran', 'Louis'...
2      2008-01-13  ...                           [['Pan', 'Hongjun', '']]
3      2007-05-23  ...                          [['Callan', 'David', '']]
4      2013-10-15  ...  [['Abu-Shammala', 'Wael', ''], ['Torchinsky', ...
...           ...  ...                                                ...
39995  2008-11-26  ...  [['Nomura', 'Yasunori', ''], ['Papucci', 'Mich...
39996  2011-07-20  ...  [['Berg', 'Chris', ''], ['Vazirani', 'Monica',...
39997  2007-12-20  ...  [['Ganyushkin', 'Olexandr', ''], ['Mazorchuk',...
39998  2009-11-13  ...  [['Harris', 'Jason', ''], ['Zaritsky', 'Dennis...
39999  2007-12-14  ...  [['Gemba', 'K.', ''], ['Hlousek', 'Z. T.', '']...

[40000 rows x 14 columns]

### Data Preprocessing

In [ ]:
dataset.isnull().sum()

update_date           0
title                 0
journal-ref       19270
submitter             0
authors               0
doi               15629
comments           4709
categories            0
abstract              0
id                    0
license           36261
report-no         36055
versions              0
authors_parsed        0
dtype: int64

In [ ]:
dataset = dataset.drop(columns=['update_date','title','journal-ref','submitter','authors','doi','comments','id','license','report-no','versions','authors_parsed'],axis=1)
dataset

            categories                                           abstract
0               hep-ph    A fully differential calculation in perturba...
1        math.CO cs.CG    We describe a new algorithm, the $(k,\ell)$-...
2       physics.gen-ph    The evolution of Earth-Moon system is descri...
3              math.CO    We show that a determinant of Stirling cycle...
4      math.CA math.FA    In this paper we show how to compute the $\L...
...                ...                                                ...
39995           hep-ph    Weak scale supersymmetry provides elegant so...
39996  math.CO math.RT    In this paper we give an alternate combinato...
39997  math.RT math.GR    Work of Clifford, Munn and Ponizovski{\u\i} ...
39998         astro-ph    We present a detailed reconstruction of the ...
39999         quant-ph    In quantum mechanics with minimal length unc...

[40000 rows x 2 columns]

In [ ]:
threshold = 100
val_counts = dataset['categories'].value_counts()
rare_categories = val_counts[val_counts < threshold].index
dataset['categories'] = dataset['categories'].apply(
    lambda x: 'other' if x in rare_categories else x
)

In [ ]:
dataset['categories'].value_counts()

categories
other                                  14039
astro-ph                                6720
hep-ph                                  2222
quant-ph                                1723
hep-th                                  1525
cond-mat.mtrl-sci                        843
gr-qc                                    804
cond-mat.mes-hall                        697
hep-ex                                   632
nucl-th                                  586
cond-mat.str-el                          575
cond-mat.stat-mech                       530
math-ph math.MP                          466
cond-mat.other                           447
math.PR                                  433
math.AG                                  397
math.CO                                  353
hep-lat                                  352
cs.IT math.IT                            337
math.DG                                  334
nucl-ex                                  312
math.NT                                  306
cond-mat.soft                            301
cond-mat.supr-con                        297
physics.gen-ph                           291
math.AP                                  243
physics.optics                           219
math.ST stat.TH                          219
cond-mat.supr-con cond-mat.str-el        201
hep-th gr-qc                             181
math.CA                                  170
math.GT                                  165
physics.atom-ph                          163
math.DS                                  163
hep-ph hep-ex                            160
cond-mat.str-el cond-mat.mtrl-sci        152
cond-mat.mes-hall cond-mat.mtrl-sci      144
cond-mat.soft cond-mat.stat-mech         143
math.RT                                  139
cond-mat.mes-hall cond-mat.str-el        137
gr-qc hep-th                             137
hep-th hep-ph                            137
gr-qc astro-ph hep-th                    129
cond-mat.str-el cond-mat.supr-con        125
nlin.CD                                  121
physics.soc-ph                           121
physics.ins-det                          117
gr-qc astro-ph                           115
math.FA                                  115
math.GR                                  114
cs.AR                                    114
cond-mat.stat-mech cond-mat.soft         110
astro-ph hep-ph                          109
hep-ph hep-th                            109
cond-mat.mtrl-sci cond-mat.other         106
cond-mat.dis-nn                          100
Name: count, dtype: int64

In [ ]:
len(dataset['categories'].value_counts())

56

## Create the BertTopic unsupervised Model 1

In [ ]:
embedding_model = SentenceTransformer("all-MiniLM-L12-v2")

# Step 2 - Reduce dimensionality
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine')

# Step 3 - Cluster reduced embeddings
hdbscan_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)

# Step 4 - Tokenize topics
vectorizer_model = CountVectorizer(stop_words="english")

# Step 5 - Create topic representation
ctfidf_model = ClassTfidfTransformer()

# Step 6 - (Optional) Fine-tune topic representations with
# a `bertopic.representation` model
representation_model = KeyBERTInspired()

# All steps together
topic_model = BERTopic(
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  umap_model=umap_model,                    # Step 2 - Reduce dimensionality
  hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic representations
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/352 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
topics,probs = topic_model.fit_transform(dataset['abstract'])

### Evaluation

In [ ]:
embeddings = topic_model.umap_model.embedding_
mask = np.array(topics) != -1
filtered_topics = np.array(topics)[mask]

print(f"Silhouette: {silhouette_score(embeddings[mask], filtered_topics):.3f}")
print(f"CH Index: {calinski_harabasz_score(embeddings[mask], filtered_topics):.0f}")

Silhouette: 0.549
CH Index: 45958

### The most frequent topics

In [ ]:
topic_model.get_topic_info()

     Topic  ...                                Representative_Docs
0       -1  ...  [  (Abridged version) We present the first det...
1        0  ...  [  We explore the Higgs sector in the supersym...
2        1  ...  [  It is shown that the use of a density depen...
3        2  ...  [  We study the behaviour of the Ricci Yang-Mi...
4        3  ...  [  We consider a state-dependent full-duplex r...
..     ...  ...                                                ...
271    270  ...  [  We outline the qualitatively different phys...
272    271  ...  [  Due to recent successes of a statistical-ba...
273    272  ...  [  [Abridged] We present a comprehensive study...
274    273  ...  [  We investigate the physical property of the...
275    274  ...  [  To any infinite word w over a finite alphab...

[276 rows x 5 columns]

### Frequent words from the second most frequent topic

In [ ]:
topic_model.get_topic(0)

[('higgs', np.float32(0.62909603)),
 ('lhc', np.float32(0.5741783)),
 ('quark', np.float32(0.47447482)),
 ('quarks', np.float32(0.46800107)),
 ('bosons', np.float32(0.45707306)),
 ('supersymmetry', np.float32(0.44903964)),
 ('supersymmetric', np.float32(0.41509786)),
 ('lepton', np.float32(0.3498004)),
 ('gauge', np.float32(0.34151113)),
 ('fermion', np.float32(0.33840704))]

### Info about the documents clustered in these topics

In [ ]:
topic_model.get_document_info(dataset['abstract'])

                                                Document  ...  Representative_document
0        A fully differential calculation in perturba...  ...                    False
1        We describe a new algorithm, the $(k,\ell)$-...  ...                    False
2        The evolution of Earth-Moon system is descri...  ...                    False
3        We show that a determinant of Stirling cycle...  ...                    False
4        In this paper we show how to compute the $\L...  ...                    False
...                                                  ...  ...                      ...
39995    Weak scale supersymmetry provides elegant so...  ...                    False
39996    In this paper we give an alternate combinato...  ...                    False
39997    Work of Clifford, Munn and Ponizovski{\u\i} ...  ...                    False
39998    We present a detailed reconstruction of the ...  ...                    False
39999    In quantum mechanics with minimal length unc...  ...                    False

[40000 rows x 8 columns]

## Data Visualization of the topics

In [ ]:
topic_model.visualize_barchart(top_n_topics=20,n_words=10)

In [ ]:
topic_model.visualize_heatmap()

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_term_rank()

In [ ]:
topic_model.visualize_hierarchy()

In [ ]:
topics_per_class = topic_model.topics_per_class(dataset['abstract'], classes=dataset['categories'])
topic_model.visualize_topics_per_class(topics_per_class)

## Create BertTopic supervised model 1

In [ ]:
X,y= dataset.drop(columns=['categories'],axis=1),dataset['categories']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
embedding_model = SentenceTransformer("all-MiniLM-L12-v2")

# Step 2 - Reduce dimensionality
umap_model = BaseDimensionalityReduction()

# Step 3 - Cluster reduced embeddings
hdbscan_model = LogisticRegression()

# Step 5 - Create topic representation
ctfidf_model = ClassTfidfTransformer()

# Step 6 - (Optional) Fine-tune topic representations with
# a `bertopic.representation` model
representation_model = KeyBERTInspired()

# All steps together
topic_model = BERTopic(
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  umap_model=umap_model,                    # Step 2 - Reduce dimensionality
  hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic representations
)

In [ ]:
X_train = X_train.squeeze().astype(str).tolist()

In [ ]:
y_train = y_train.squeeze().astype(str).tolist()

In [ ]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_train_encoded

array([49, 49,  0, ...,  0,  0,  0])

In [ ]:
topics, probs = topic_model.fit_transform(X_train, y=y_train_encoded)

### Details about the topic frequency

In [ ]:
topic_info_df = topic_model.get_topic_info()
topic_info_df["Class_Label"] = topic_info_df["Topic"].apply(
    lambda t: encoder.inverse_transform([t])[0] if t >= 0 and t < len(encoder.classes_) else "Other"
)
topic_info_df

    Topic  ...                          Class_Label
0       0  ...                             astro-ph
1       1  ...                      astro-ph hep-ph
2       2  ...                      cond-mat.dis-nn
3       3  ...                    cond-mat.mes-hall
4       4  ...  cond-mat.mes-hall cond-mat.mtrl-sci
5       5  ...    cond-mat.mes-hall cond-mat.str-el
6       6  ...                    cond-mat.mtrl-sci
7       7  ...     cond-mat.mtrl-sci cond-mat.other
8       8  ...                       cond-mat.other
9       9  ...                        cond-mat.soft
10     10  ...     cond-mat.soft cond-mat.stat-mech
11     11  ...                   cond-mat.stat-mech
12     12  ...     cond-mat.stat-mech cond-mat.soft
13     13  ...                      cond-mat.str-el
14     14  ...    cond-mat.str-el cond-mat.mtrl-sci
15     15  ...    cond-mat.str-el cond-mat.supr-con
16     16  ...                    cond-mat.supr-con
17     17  ...    cond-mat.supr-con cond-mat.str-el
18     18  ...                                cs.AR
19     19  ...                        cs.IT math.IT
20     20  ...                                gr-qc
21     21  ...                       gr-qc astro-ph
22     22  ...                gr-qc astro-ph hep-th
23     23  ...                         gr-qc hep-th
24     24  ...                               hep-ex
25     25  ...                              hep-lat
26     26  ...                               hep-ph
27     27  ...                        hep-ph hep-ex
28     28  ...                        hep-ph hep-th
29     29  ...                               hep-th
30     30  ...                         hep-th gr-qc
31     31  ...                        hep-th hep-ph
32     32  ...                      math-ph math.MP
33     33  ...                              math.AG
34     34  ...                              math.AP
35     35  ...                              math.CA
36     36  ...                              math.CO
37     37  ...                              math.DG
38     38  ...                              math.DS
39     39  ...                              math.FA
40     40  ...                              math.GR
41     41  ...                              math.GT
42     42  ...                              math.NT
43     43  ...                              math.PR
44     44  ...                              math.RT
45     45  ...                      math.ST stat.TH
46     46  ...                              nlin.CD
47     47  ...                              nucl-ex
48     48  ...                              nucl-th
49     49  ...                                other
50     50  ...                      physics.atom-ph
51     51  ...                       physics.gen-ph
52     52  ...                      physics.ins-det
53     53  ...                       physics.optics
54     54  ...                       physics.soc-ph
55     55  ...                             quant-ph

[56 rows x 6 columns]

### Frequent words from the second most frequent topic

In [ ]:
topic_model.get_topic(0)

[('dynamics', np.float32(0.44298545)),
 ('quantum', np.float32(0.3275764)),
 ('density', np.float32(0.30828282)),
 ('numerical', np.float32(0.24250662)),
 ('theory', np.float32(0.23960298)),
 ('phase', np.float32(0.21765576)),
 ('spin', np.float32(0.21119249)),
 ('energy', np.float32(0.20504196)),
 ('lattice', np.float32(0.20408583)),
 ('temperature', np.float32(0.20305517))]

## Data visualization of the topics

In [ ]:
topic_model.visualize_barchart(top_n_topics=20,n_words=10)

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_hierarchy()

In [ ]:
X_test = X_test.squeeze().astype(str).tolist()
predicted_topics, _ = topic_model.transform(X_test)

In [ ]:
predicted_labels = encoder.inverse_transform(predicted_topics)

In [ ]:
y_test = y_test.squeeze().astype(str).tolist()
print(classification_report(y_test,predicted_labels,zero_division=0))

                                     precision    recall  f1-score   support

                           astro-ph       0.02      0.05      0.03      1265
                    astro-ph hep-ph       0.01      0.60      0.02        20
                    cond-mat.dis-nn       0.00      0.00      0.00        15
                  cond-mat.mes-hall       0.02      0.04      0.02       141
cond-mat.mes-hall cond-mat.mtrl-sci       0.00      0.00      0.00        23
  cond-mat.mes-hall cond-mat.str-el       0.01      0.06      0.02        32
                  cond-mat.mtrl-sci       0.00      0.00      0.00       178
   cond-mat.mtrl-sci cond-mat.other       0.01      0.09      0.02        22
                     cond-mat.other       0.00      0.00      0.00        96
                      cond-mat.soft       0.00      0.00      0.00        59
   cond-mat.soft cond-mat.stat-mech       0.00      0.00      0.00        35
                 cond-mat.stat-mech       0.50      0.22      0.30       116
   cond-mat.stat-mech cond-mat.soft       0.00      0.00      0.00        22
                    cond-mat.str-el       0.00      0.00      0.00       110
  cond-mat.str-el cond-mat.mtrl-sci       0.00      0.00      0.00        32
  cond-mat.str-el cond-mat.supr-con       0.00      0.00      0.00        19
                  cond-mat.supr-con       0.00      0.00      0.00        63
  cond-mat.supr-con cond-mat.str-el       0.00      0.00      0.00        33
                              cs.AR       0.00      0.00      0.00        28
                      cs.IT math.IT       0.00      0.00      0.00        62
                              gr-qc       0.00      0.00      0.00       164
                     gr-qc astro-ph       0.00      0.00      0.00        36
              gr-qc astro-ph hep-th       0.00      0.00      0.00        24
                       gr-qc hep-th       0.00      0.00      0.00        25
                             hep-ex       0.00      0.00      0.00       133
                            hep-lat       0.00      0.00      0.00        73
                             hep-ph       0.00      0.00      0.00       439
                      hep-ph hep-ex       0.00      0.00      0.00        41
                      hep-ph hep-th       0.00      0.00      0.00        23
                             hep-th       0.00      0.00      0.00       309
                       hep-th gr-qc       0.00      0.00      0.00        26
                      hep-th hep-ph       0.00      0.00      0.00        31
                    math-ph math.MP       0.00      0.00      0.00        81
                            math.AG       0.00      0.00      0.00        75
                            math.AP       0.00      0.00      0.00        54
                            math.CA       0.00      0.00      0.00        32
                            math.CO       0.00      0.00      0.00        82
                            math.DG       0.00      0.00      0.00        70
                            math.DS       0.00      0.00      0.00        34
                            math.FA       0.00      0.00      0.00        21
                            math.GR       0.00      0.00      0.00        25
                            math.GT       0.00      0.00      0.00        42
                            math.NT       0.00      0.00      0.00        55
                            math.PR       0.00      0.00      0.00       100
                            math.RT       0.00      0.00      0.00        33
                    math.ST stat.TH       0.00      0.00      0.00        50
                            nlin.CD       0.00      0.00      0.00        18
                            nucl-ex       0.00      0.00      0.00        58
                            nucl-th       0.00      0.00      0.00       115
                              other       0.00      0.00      0.00      2867
                    physics.atom-ph       0.00      0.00      0.00        25
                     physics.gen-ph       0.00      0.00      0.00        53
                    physics.ins-det       0.00      0.00      0.00        22
                     physics.optics       0.00      0.00      0.00        39
                     physics.soc-ph       0.00      0.00      0.00        20
                           quant-ph       0.00      0.00      0.00       334

                           accuracy                           0.01      8000
                          macro avg       0.01      0.02      0.01      8000
                       weighted avg       0.01      0.01      0.01      8000

## Create BertTopic Model unsupervised 2

In [ ]:
embedding_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")

# Step 2 - Reduce dimensionality
umap_model = UMAP(n_components=5, metric='cosine', random_state=42)

# Step 3 - Cluster reduced embeddings
hdbscan_model = KMeans()

# Step 4 - Tokenize topics
vectorizer_model = TfidfVectorizer(stop_words="english")


# Step 6 - (Optional) Fine-tune topic representations with
# a `bertopic.representation` model
representation_model = MaximalMarginalRelevance(diversity=0.3)

# All steps together
topic_model_2 = BERTopic(
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  umap_model=umap_model,                    # Step 2 - Reduce dimensionality
  hdbscan_model=hdbscan_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic representations
)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.51k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
topics, _ = topic_model_2.fit_transform(dataset['abstract'])

### Evaluation

In [ ]:
embeddings = topic_model_2.umap_model.embedding_
mask = np.array(topics) != -1
filtered_topics = np.array(topics)[mask]

print(f"Silhouette: {silhouette_score(embeddings[mask], filtered_topics):.3f}")
print(f"CH Index: {calinski_harabasz_score(embeddings[mask], filtered_topics):.0f}")

Silhouette: 0.442
CH Index: 44833

### The most frequent topics

In [ ]:
topic_model_2.get_topic_info()

   Topic  ...                                Representative_Docs
0      0  ...  [  We consider algebras in a modular tensor ca...
1      1  ...  [  A 10-arcmin field around the HDF(N) contain...
2      2  ...  [  The insulating magnetic phase in graphene z...
3      3  ...  [  B decays are a subject of active research s...
4      4  ...  [  In the present paper we study the entanglem...
5      5  ...  [  Many important real-world networks manifest...
6      6  ...  [  The $sp(8, R)$ invariant formulation of fre...
7      7  ...  [  We study non-linear structure formation in ...

[8 rows x 5 columns]

### Frequent words from the second most frequent topic

In [ ]:
topic_model_2.get_topic(0)

[('algebras', np.float64(0.01755437002489335)),
 ('finite', np.float64(0.017468134158072624)),
 ('groups', np.float64(0.015786288861467396)),
 ('spaces', np.float64(0.015054440666585884)),
 ('cohomology', np.float64(0.014489989475501166)),
 ('theorem', np.float64(0.01415379475693976)),
 ('lie', np.float64(0.012777469126203754)),
 ('theory', np.float64(0.012580671724332571)),
 ('complex', np.float64(0.011908767830186325)),
 ('manifold', np.float64(0.010943386121941137))]

### Info about the documents clustered in these topics

In [ ]:
topic_model_2.get_document_info(dataset['abstract'])

                                                Document  ...  Representative_document
0        A fully differential calculation in perturba...  ...                    False
1        We describe a new algorithm, the $(k,\ell)$-...  ...                    False
2        The evolution of Earth-Moon system is descri...  ...                    False
3        We show that a determinant of Stirling cycle...  ...                    False
4        In this paper we show how to compute the $\L...  ...                    False
...                                                  ...  ...                      ...
39995    Weak scale supersymmetry provides elegant so...  ...                    False
39996    In this paper we give an alternate combinato...  ...                    False
39997    Work of Clifford, Munn and Ponizovski{\u\i} ...  ...                    False
39998    We present a detailed reconstruction of the ...  ...                    False
39999    In quantum mechanics with minimal length unc...  ...                    False

[40000 rows x 7 columns]

## Visualization of the topics

In [ ]:
topic_model_2.visualize_barchart(top_n_topics=20,n_words=8)

In [ ]:
topic_model_2.visualize_heatmap()

In [ ]:
topic_model_2.visualize_topics()

In [ ]:
topic_model_2.visualize_term_rank()

In [ ]:
topic_model_2.visualize_hierarchy()

In [ ]:
topics_per_class = topic_model_2.topics_per_class(dataset['abstract'], classes=dataset['categories'])
topic_model_2.visualize_topics_per_class(topics_per_class)